config/routes.rb
Rails.application.routes.draw do
  get 'user/create'
  post 'user/create'
  get 'user/new'
  get 'user/show'
  get 'user/destroy'
  get 'user/index'
  post 'user/index'

  root 'user#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def new
  end

  def create
  	@user = User.new
  end

  def show
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>Registration</h1>
<%= form_for @user, url: user_create_path do |f| %>
  <%= f.text_field :name %><br>
  <%= f.text_field :password %><br>
  <%= f.email_field :email %><br>
  <%= f.submit "Registration" %>
  <%= link_to "SignUp", user_new_path %>
<% end %>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/new.html.erb
<h1>Registration</h1>
<%= form_for :user, urL: {action: "create"} do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
 
  <p>
    <%= form.label :Password %><br>
    <%= form.password_field :Password %><br>
    <%= form.password_field :Password %>
  </p>
 
  <p>
    <%= form.label :Email %><br>
    <%= form.email_field :Email %>
  </p>
 

  <p>
    <%= form.submit %>
    <a href = <%= new_path %>>Login</a>
<% end %>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>